# Docker Compose configuration for groxpi testing with MinIO
# Usage: docker-compose -f docker-compose.test.yml up -d

version: '3.8'

services:
  # MinIO S3-compatible storage for testing
  minio-test:
    image: minio/minio:latest
    container_name: groxpi-minio-test
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web Console
    volumes:
      - minio_test_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - test-network

  # MinIO Client for test bucket initialization
  minio-init:
    image: minio/mc:latest
    container_name: groxpi-minio-init
    depends_on:
      minio-test:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc config host add minio-test http://minio-test:9000 minioadmin minioadmin;
      mc mb -p minio-test/groxpi-test;
      mc policy set public minio-test/groxpi-test;
      echo 'Test bucket groxpi-test created successfully';
      exit 0;
      "
    networks:
      - test-network

volumes:
  minio_test_data:
    driver: local

networks:
  test-network:
    driver: bridge